// Package main is the Agnos Hospital Middleware API.
//
//	@title			Agnos Hospital Middleware API
//	@version		1.0
//	@description	Middleware for searching/displaying patient information across hospitals, with per-hospital staff isolation.
//	@BasePath		/
//
//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
//	@description				Type "Bearer" followed by a space and the access token, e.g. "Bearer eyJhbGc..."
package main

import (
	"encoding/base64"
	"log"
	"net/http"
	"os"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	_ "github.com/watt-siwat/agnos-backend/docs" // swagger docs, generated by `swag init`
	appcrypto "github.com/watt-siwat/agnos-backend/internal/crypto"
	"github.com/watt-siwat/agnos-backend/internal/dbmigrate"
	"github.com/watt-siwat/agnos-backend/internal/handler"
	"github.com/watt-siwat/agnos-backend/internal/middleware"
	"github.com/watt-siwat/agnos-backend/internal/mockhis"
	"github.com/watt-siwat/agnos-backend/internal/repository"
	"github.com/watt-siwat/agnos-backend/internal/service"
	"github.com/watt-siwat/agnos-backend/webui"
)

func mustEnv(key string) string {
	v := os.Getenv(key)
	if v == "" {
		log.Fatalf("missing required env var %s", key)
	}
	return v
}

func main() {
	dsn := mustEnv("DATABASE_URL")
	jwtSecret := []byte(mustEnv("JWT_SECRET"))
	encKeyB64 := mustEnv("ENCRYPTION_KEY")
	hmacSecret := mustEnv("HMAC_SECRET")

	encKey, err := base64.StdEncoding.DecodeString(encKeyB64)
	if err != nil {
		log.Fatalf("decode ENCRYPTION_KEY (expected base64): %v", err)
	}
	cryptor, err := appcrypto.New(encKey, []byte(hmacSecret))
	if err != nil {
		log.Fatalf("init crypto: %v", err)
	}

	// Self-migrating: idempotent, safe on every boot. Required for platforms
	// (Railway, Fly, Render) that don't offer a separate pre-deploy migration
	// step the way the old docker-compose init container did.
	if err := dbmigrate.Apply(dsn); err != nil {
		log.Fatalf("apply migrations: %v", err)
	}

	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		log.Fatalf("connect db: %v", err)
	}

	hospitalRepo := repository.NewHospitalRepository(db)
	staffRepo := repository.NewStaffRepository(db)
	patientRepo := repository.NewPatientRepository(db)
	refreshTokenRepo := repository.NewRefreshTokenRepository(db)

	authService := service.NewAuthService(hospitalRepo, staffRepo, refreshTokenRepo, jwtSecret)
	patientService := service.NewPatientService(patientRepo, cryptor)

	staffHandler := handler.NewStaffHandler(authService)
	patientHandler := handler.NewPatientHandler(patientService)

	r := gin.Default()
	if os.Getenv("ENABLE_DEV_CORS") == "true" {
		r.Use(middleware.CORS()) // permissive, dev-only — enables the local test UI (webui/)
	}

	r.GET("/healthz", func(c *gin.Context) { c.JSON(200, gin.H{"status": "ok"}) })
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Test console (webui/) — a testing aid, not the graded front-end
	// deliverable. Embedded into the binary so it's reachable wherever the
	// API is deployed, no separate static server required.
	//
	// Read+Data instead of FileFromFS/http.FileServer — the stdlib file
	// server special-cases any file named index.html and 301s to "./" when
	// the request path doesn't end in "/", which breaks a clean /ui path.
	r.GET("/ui", func(c *gin.Context) {
		data, err := webui.FS.ReadFile("index.html")
		if err != nil {
			c.AbortWithStatus(http.StatusInternalServerError)
			return
		}
		c.Data(http.StatusOK, "text/html; charset=utf-8", data)
	})

	// Mock Hospital A HIS — standalone simulator, task 1 of the assignment.
	r.GET("/mock-his/patient/search/:id", mockhis.Search)

	r.POST("/staff/login", staffHandler.Login)
	r.POST("/staff/refresh", staffHandler.Refresh) // bonus, beyond stated spec

	authorized := r.Group("/")
	authorized.Use(middleware.JWTAuth(jwtSecret))
	{
		authorized.POST("/staff/create", staffHandler.Create)
		authorized.GET("/patient/search", patientHandler.Search)
		authorized.POST("/staff/logout", staffHandler.Logout) // bonus, beyond stated spec
	}

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("server error: %v", err)
	}
}
