// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mock-his/patient/search/{id}": {
            "get": {
                "description": "Standalone simulator of the external Hospital A HIS API (task 1). Hardcoded in-memory fixtures, not called by the middleware's own /patient/search.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mock-his"
                ],
                "summary": "Mock Hospital A HIS patient lookup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "national_id or passport_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_mockhis.patientRecord"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/patient/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "All filters are optional and AND-ed together. Identifiers/phone/email/DOB are exact match; name fields are partial match across Thai and English columns. Results are always scoped to the caller's own hospital, and paginated.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patient"
                ],
                "summary": "Search patients",
                "parameters": [
                    {
                        "type": "string",
                        "description": "exact match",
                        "name": "national_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "exact match",
                        "name": "passport_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "partial match, TH or EN",
                        "name": "first_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "partial match, TH or EN",
                        "name": "middle_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "partial match, TH or EN",
                        "name": "last_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD, exact match",
                        "name": "date_of_birth",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "exact match",
                        "name": "phone_number",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "exact match",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "default 20, capped at 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "default 0",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_watt-siwat_agnos-backend_internal_service.PatientSearchResult"
                        }
                    },
                    "400": {
                        "description": "invalid date_of_birth, limit, or offset",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "missing or invalid token",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/staff/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Requires auth; the target hospital must match the caller's own hospital.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Create a new staff member",
                "parameters": [
                    {
                        "description": "New staff details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.createStaffRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "unknown hospital or username taken",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "missing or invalid token",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "403": {
                        "description": "hospital does not match caller's hospital",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/staff/login": {
            "post": {
                "description": "Verifies credentials scoped to a hospital and issues an access + refresh token pair.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Staff login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.tokenPairResponse"
                        }
                    },
                    "401": {
                        "description": "invalid username, password, or hospital",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/staff/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Bonus endpoint, beyond the assignment's stated spec. Deletes the presented refresh token so it cannot be used again.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Revoke a refresh token",
                "parameters": [
                    {
                        "description": "Refresh token to revoke",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.logoutRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "401": {
                        "description": "missing or invalid access token",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/staff/refresh": {
            "post": {
                "description": "Bonus endpoint, beyond the assignment's stated spec. Rotates: the presented refresh token is invalidated and a new pair is issued.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Rotate an access/refresh token pair",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.tokenPairResponse"
                        }
                    },
                    "401": {
                        "description": "invalid, expired, or already-rotated refresh token",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_watt-siwat_agnos-backend_internal_service.PatientDTO": {
            "type": "object",
            "properties": {
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name_en": {
                    "type": "string"
                },
                "first_name_th": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name_en": {
                    "type": "string"
                },
                "last_name_th": {
                    "type": "string"
                },
                "middle_name_en": {
                    "type": "string"
                },
                "middle_name_th": {
                    "type": "string"
                },
                "national_id": {
                    "type": "string"
                },
                "passport_id": {
                    "type": "string"
                },
                "patient_hn": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "github_com_watt-siwat_agnos-backend_internal_service.PatientSearchResult": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "patients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_watt-siwat_agnos-backend_internal_service.PatientDTO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.createStaffRequest": {
            "type": "object",
            "required": [
                "hospital",
                "password",
                "username"
            ],
            "properties": {
                "hospital": {
                    "type": "string",
                    "example": "hospital_a"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handler.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_handler.loginRequest": {
            "type": "object",
            "required": [
                "hospital",
                "password",
                "username"
            ],
            "properties": {
                "hospital": {
                    "type": "string",
                    "example": "hospital_a"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handler.logoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_handler.refreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_handler.tokenPairResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_mockhis.patientRecord": {
            "type": "object",
            "properties": {
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name_en": {
                    "type": "string"
                },
                "first_name_th": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "last_name_en": {
                    "type": "string"
                },
                "last_name_th": {
                    "type": "string"
                },
                "middle_name_en": {
                    "type": "string"
                },
                "middle_name_th": {
                    "type": "string"
                },
                "national_id": {
                    "type": "string"
                },
                "passport_id": {
                    "type": "string"
                },
                "patient_hn": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the access token, e.g. \"Bearer eyJhbGc...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Agnos Hospital Middleware API",
	Description:      "Middleware for searching/displaying patient information across hospitals, with per-hospital staff isolation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
